packagesApt=(
  "flatpak"
  "gcc"
  "xclip"
  "neofetch"
  "build-essential"
  "curl"
  "zsh"
  "git"
  "neovim"
  "firefox"
  "google-chrome-stable"
  "pgadmin4"
  "docker-ce"
  "docker-ce-cli"
  "containerd.io"
  "docker-buildx-plugin"
  "docker-compose-plugin"
  "1password"
  "spotify-client"
  "gnome-tweaks"
  "gnome-shell-extension-manager"
  "teams-for-linux"
  "insomnia"
)

packagesFlatpak=(
  "slack"
  "redisinsight"
)

packagesBrew=(
  "zsh-autosuggestions"
  "zsh-syntax-highlighting"
  "gh"
  "lazygit"
  "asdf"
  "kubernetes-cli"
  "azure-cli"
  "Azure/kubelogin/kubelogin"
  "k9s"
  "jesseduffield/lazydocker/lazydocker"
)

